### ISSUE TITLE
[FR] Please add a way of toggling the UI

### ISSUE THREAD

**Issue by rob-a-bolton** [zuzak/yakc#22]
The ability to toggle the UI would allow users to view video content which would otherwise be obscured by the UI.

**Comment by zuzak** [comment]
I'm not sure what the use-case is. Which parts of the UI get in the way? Which videos need it?
My worry is that having a minimise UI button will (ironically) clutter the UI for everyone else, and I don't want to make it hard for users to find and use the up/down/shunt/etc moderation buttons.

At the moment, if you view the website at a particularly small resolution (≤600px wide) many of the UI elements abbreviate or are hidden entirely. Should that take place on wider screens?

Another problem is persistence: due to how form submission works, a state that would remain on page refresh wouldn't necessarily remain through the form submission and page redirection process that moderation entails. Would it be okay if it only worked on a video to video basis?
